version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: front
    expose:
      - "9000"

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: back
    expose:
      - "5252"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
